spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${FINCORE_DB_URL}
    username: ${FINCORE_DB_USER}
    password: ${FINCORE_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${FINCORE_KAFKA_BOOTSTRAP}

fincore:
  security:
    api-key:
      write-key: ${FINCORE_API_KEY_WRITE}
      read-only-key: ${FINCORE_API_KEY_READ_ONLY}
